"""Create the 27-page APA-style report for the executed joint torus SSM."""

from __future__ import annotations

import json
import math
import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import HRFlowable, Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
REPORT = ROOT / "report"
FIG = REPORT / "figures"
PDF = REPORT / "Signals_Project_APA_Report.pdf"
ANALYTICAL = "Analytical joint score"
SURROGATE = "Amortized joint surrogate"


def setup_fonts() -> None:
    runtime = Path(os.environ.get("CODEX_PRIMARY_RUNTIME_ROOT", "/opt/codex/runtimes/codex-primary-runtime"))
    folder = runtime / "dependencies/native/libreoffice-headless/libreoffice/share/fonts/truetype"
    for name, filename in [("APA", "LiberationSerif-Regular.ttf"), ("APA-Bold", "LiberationSerif-Bold.ttf"), ("APA-Italic", "LiberationSerif-Italic.ttf")]:
        path = folder / filename
        if path.exists():
            pdfmetrics.registerFont(TTFont(name, str(path)))


def styles() -> dict[str, ParagraphStyle]:
    setup_fonts()
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Title"], fontName="APA-Bold", fontSize=21, leading=27, alignment=TA_CENTER, spaceAfter=18),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"], fontName="APA", fontSize=12, leading=20, alignment=TA_CENTER, spaceAfter=12),
        "h1": ParagraphStyle("h1", parent=base["Heading1"], fontName="APA-Bold", fontSize=15, leading=19, spaceAfter=10, keepWithNext=True),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], fontName="APA-Bold", fontSize=11.5, leading=15, spaceBefore=6, spaceAfter=4, keepWithNext=True),
        "body": ParagraphStyle("body", parent=base["BodyText"], fontName="APA", fontSize=10.2, leading=15.2, firstLineIndent=.27*inch, alignment=TA_LEFT, spaceAfter=7),
        "body0": ParagraphStyle("body0", parent=base["BodyText"], fontName="APA", fontSize=10.2, leading=15.2, alignment=TA_LEFT, spaceAfter=7),
        "small": ParagraphStyle("small", parent=base["BodyText"], fontName="APA", fontSize=8.2, leading=10.5, spaceAfter=3),
        "caption": ParagraphStyle("caption", parent=base["BodyText"], fontName="APA-Italic", fontSize=8.5, leading=11, spaceBefore=4, spaceAfter=6),
        "bullet": ParagraphStyle("bullet", parent=base["BodyText"], fontName="APA", fontSize=9.8, leading=14.5, leftIndent=.25*inch, firstLineIndent=-.14*inch, bulletIndent=.08*inch, spaceAfter=4),
        "ref": ParagraphStyle("ref", parent=base["BodyText"], fontName="APA", fontSize=8.8, leading=12.4, leftIndent=.24*inch, firstLineIndent=-.24*inch, spaceAfter=5),
        "center": ParagraphStyle("center", parent=base["BodyText"], fontName="APA", fontSize=10.2, leading=15.2, alignment=TA_CENTER, spaceAfter=7),
    }


def p(text: str, sty: dict[str, ParagraphStyle], name: str = "body") -> Paragraph:
    return Paragraph(text, sty[name])


def bullets(items: list[str], sty: dict[str, ParagraphStyle]) -> list[Paragraph]:
    return [Paragraph("• " + item, sty["bullet"]) for item in items]


def table(rows: list[list[object]], widths: list[float], sty: dict[str, ParagraphStyle], header: bool = True) -> Table:
    cooked = [[Paragraph(str(value), sty["small"]) for value in row] for row in rows]
    item = Table(cooked, colWidths=widths, repeatRows=1 if header else 0, hAlign="LEFT")
    rules = [("VALIGN",(0,0),(-1,-1),"TOP"),("GRID",(0,0),(-1,-1),.35,colors.HexColor("#aab3bd")),("LEFTPADDING",(0,0),(-1,-1),5),("RIGHTPADDING",(0,0),(-1,-1),5),("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4)]
    if header:
        rules += [("BACKGROUND",(0,0),(-1,0),colors.HexColor("#dbe8ef")),("FONTNAME",(0,0),(-1,0),"APA-Bold")]
    item.setStyle(TableStyle(rules))
    return item


def image(name: str, width: float = 6.55*inch, height: float = 2.45*inch) -> Image:
    item = Image(str(FIG / name), width=width, height=height)
    item.hAlign = "CENTER"
    return item


def add_page(story: list, title: str, elements: list, sty: dict[str, ParagraphStyle], number: int) -> None:
    story.append(Paragraph(title, sty["h1"]))
    story.append(HRFlowable(width="100%", thickness=.55, color=colors.HexColor("#697680"), spaceAfter=10))
    story.extend(elements)
    if number < 27:
        story.append(PageBreak())


def page_number(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("APA", 9)
    canvas.setFillColor(colors.HexColor("#4d5964"))
    canvas.drawRightString(7.55*inch, 10.35*inch, str(doc.page))
    canvas.restoreState()


def make_figures(results: pd.DataFrame, cells: pd.DataFrame, pairs: pd.DataFrame, trace: pd.DataFrame, effects: pd.DataFrame) -> None:
    FIG.mkdir(parents=True, exist_ok=True)
    plt.rcParams.update({"font.family":"DejaVu Serif","font.size":8.5,"axes.spines.top":False,"axes.spines.right":False})
    cyan, amber, violet, green = "#1284a6", "#d78b16", "#7654b2", "#2f9a67"
    order = [ANALYTICAL, SURROGATE]
    endpoints = ["mse_frequency","phase_circular_rmse","channel_nmse","particle_ess_mean","latency_ms_per_sample"]
    labels = ["Frequency\nMSE", "Phase RMSE\n(rad)", "Channel\nNMSE", "Particle\nESS", "Latency\n(ms/sample)"]
    means = results.groupby("architecture")[endpoints].mean().loc[order]
    ratios = means / means.loc[ANALYTICAL]
    fig, ax = plt.subplots(figsize=(6.7,2.45)); x=np.arange(len(endpoints)); w=.34
    ax.bar(x-w/2,ratios.loc[ANALYTICAL],w,color=cyan,label="Analytical"); ax.bar(x+w/2,ratios.loc[SURROGATE],w,color=amber,label="Surrogate")
    ax.axhline(1,color="#666",lw=.8); ax.set_xticks(x,labels); ax.set_ylabel("Ratio to analytical mean"); ax.grid(axis="y",alpha=.22); ax.legend(frameon=False,ncol=2)
    fig.tight_layout(); fig.savefig(FIG/"overall.png",dpi=220,bbox_inches="tight"); plt.close(fig)

    fig, axes = plt.subplots(1,3,figsize=(6.9,2.4),sharey=True)
    for ax, channel in zip(axes,["LOS","MP","NLOS"]):
        for method,color,mark in [(ANALYTICAL,cyan,"o"),(SURROGATE,amber,"s")]:
            d=cells[(cells.architecture==method)&(cells.channel==channel)].sort_values("snr_db")
            ax.errorbar(d.snr_db,d.mse_frequency_mean,yerr=1.96*d.mse_frequency_sd/np.sqrt(d.n),color=color,marker=mark,capsize=2,label=method.replace(" joint score","").replace(" joint surrogate",""))
        ax.set_title(channel,fontweight="bold"); ax.set_xlabel("SNR (dB)"); ax.grid(alpha=.2)
    axes[0].set_ylabel("Frequency MSE (Hz²)"); axes[2].legend(frameon=False,fontsize=7)
    fig.tight_layout(); fig.savefig(FIG/"factorial_mse.png",dpi=220,bbox_inches="tight"); plt.close(fig)

    fig, axes=plt.subplots(1,2,figsize=(6.8,2.45))
    for method,color,mark in [(ANALYTICAL,cyan,"o"),(SURROGATE,amber,"s")]:
        d=results[results.architecture==method].groupby("snr_db").agg(phase=("phase_circular_rmse","mean"),channel=("channel_nmse","mean")).reset_index()
        axes[0].plot(d.snr_db,d.phase,color=color,marker=mark,label=method.replace(" joint score","").replace(" joint surrogate","")); axes[1].plot(d.snr_db,d.channel,color=color,marker=mark)
    axes[0].set_ylabel("Circular RMSE (rad)"); axes[1].set_ylabel("Channel NMSE")
    for ax in axes: ax.set_xlabel("SNR (dB)"); ax.grid(alpha=.2)
    axes[0].legend(frameon=False,fontsize=7); fig.tight_layout(); fig.savefig(FIG/"phase_channel.png",dpi=220,bbox_inches="tight"); plt.close(fig)

    fig, axes=plt.subplots(1,2,figsize=(6.8,2.45))
    for method,color,mark in [(ANALYTICAL,cyan,"o"),(SURROGATE,amber,"s")]:
        d=results[results.architecture==method].groupby("snr_db").agg(ess=("particle_ess_mean","mean"),latency=("latency_ms_per_sample","mean")).reset_index()
        axes[0].plot(d.snr_db,d.ess,color=color,marker=mark,label=method.replace(" joint score","").replace(" joint surrogate","")); axes[1].plot(d.snr_db,d.latency,color=color,marker=mark)
    axes[0].set_ylabel("Mean particle ESS"); axes[1].set_ylabel("Latency (ms/sample)")
    for ax in axes: ax.set_xlabel("SNR (dB)"); ax.grid(alpha=.2)
    axes[0].legend(frameon=False,fontsize=7); fig.tight_layout(); fig.savefig(FIG/"health_compute.png",dpi=220,bbox_inches="tight"); plt.close(fig)

    pset=pairs[(pairs.group=="SNR")&(pairs.metric=="mse_frequency")].copy().sort_values("level")
    fig,ax=plt.subplots(figsize=(6.4,2.35)); x=pset.mean_difference_surrogate_minus_analytical
    ax.errorbar(x,pset.level.astype(str)+" dB",xerr=[x-pset.ci95_low,pset.ci95_high-x],fmt="o",color=violet,capsize=4); ax.axvline(0,color="#666",ls="--",lw=1); ax.set_xlabel("Paired difference: surrogate − analytical (Hz²)"); ax.grid(axis="x",alpha=.2)
    fig.tight_layout(); fig.savefig(FIG/"paired.png",dpi=220,bbox_inches="tight"); plt.close(fig)

    fig,axes=plt.subplots(1,2,figsize=(6.8,2.5))
    for method,color,style in [(ANALYTICAL,cyan,"--"),(SURROGATE,amber,":")]:
        d=trace[trace.architecture==method].sort_values("sample")
        for emitter,ax in [(1,axes[0]),(2,axes[1])]:
            if method==ANALYTICAL: ax.step(d["sample"],d[f"true_f{emitter}_hz"],where="mid",color="#222",lw=2,label="True")
            ax.plot(d["sample"],d[f"inferred_f{emitter}_hz"],style,color=color,lw=1.5,label=method.replace(" joint score","").replace(" joint surrogate",""))
            ax.set_title(f"Emitter {emitter}",fontweight="bold"); ax.set_xlabel("I/Q sample"); ax.set_ylabel("Frequency (Hz)"); ax.grid(alpha=.2)
    axes[1].legend(frameon=False,fontsize=7); fig.tight_layout(); fig.savefig(FIG/"trace.png",dpi=220,bbox_inches="tight"); plt.close(fig)

    d=trace[trace.architecture==ANALYTICAL].sort_values("sample")
    fig,axes=plt.subplots(1,2,figsize=(6.8,2.4)); axes[0].scatter(d["sample"],d.true_phase1,s=8,color="#222",label="True"); axes[0].scatter(d["sample"],d.inferred_phase1,s=8,color=cyan,label="Filtered"); axes[0].set_ylabel("Phase (rad)"); axes[0].legend(frameon=False,fontsize=7)
    axes[1].fill_between(d["sample"],d.particle_ess,color=green,alpha=.45); axes[1].plot(d["sample"],d.particle_ess,color=green); axes[1].set_ylabel("Particle ESS")
    for ax in axes: ax.set_xlabel("I/Q sample"); ax.grid(alpha=.2)
    fig.tight_layout(); fig.savefig(FIG/"torus_ess.png",dpi=220,bbox_inches="tight"); plt.close(fig)

    primary=effects[effects.response=="mse_frequency"].copy().sort_values("partial_eta_squared")
    fig,ax=plt.subplots(figsize=(6.5,2.75)); ax.barh(primary.effect,primary.partial_eta_squared,color=[green if p<.05 else "#a9b2bb" for p in primary.p_holm_within_response]); ax.set_xlabel("Partial η²"); ax.grid(axis="x",alpha=.2)
    fig.tight_layout(); fig.savefig(FIG/"effects.png",dpi=220,bbox_inches="tight"); plt.close(fig)


def main() -> None:
    REPORT.mkdir(parents=True, exist_ok=True)
    results=pd.read_csv(DATA/"joint_factorial_results.csv"); cells=pd.read_csv(DATA/"joint_cell_summary.csv"); pairs=pd.read_csv(DATA/"joint_paired_effects.csv"); trace=pd.read_csv(DATA/"joint_example_trace.csv"); effects=pd.read_csv(DATA/"joint_factorial_effects.csv"); meta=json.loads((DATA/"joint_experiment_metadata.json").read_text())
    make_figures(results,cells,pairs,trace,effects)
    sty=styles(); means=results.groupby("architecture").mean(numeric_only=True); an=means.loc[ANALYTICAL]; su=means.loc[SURROGATE]; overall={r.metric:r for r in pairs[pairs.group=="Overall"].itertuples()}; primary=effects[effects.response=="mse_frequency"].set_index("effect")
    story=[]
    story += [Spacer(1,1.2*inch),p("Signals Project",sty,"title"),p("Executed Blind De-Mixing With a Joint Torus-Valued State-Space Model",sty,"title"),Spacer(1,.25*inch),p("Exact Gaussian-Truncated-Cauchy Convolution, Latent Tapped-Delay Channels, Switching Dynamics, and Exact-Target Manifold MALA",sty,"subtitle"),Spacer(1,.55*inch),p("Signals Project Research Group",sty,"center"),p("August 27, 2026",sty,"center"),Spacer(1,.55*inch),p("Author Note",sty,"h2"),p("This report documents executable code and a completed paired simulation experiment. The evidence supports operationally representative simulation validation only. No operational or field SIGINT validation claim is made.",sty,"body0"),PageBreak()]
    add_page(story,"Abstract",[p(f"Blind separation of co-channel frequency-hopping wave packets requires joint uncertainty propagation over source states, circular phase, discrete hops, and time-varying multipath. We implemented a sequential particle filter whose particles carry two log amplitudes, frequencies, hop states, phases on the flat torus, complex tapped-delay coefficients, and delayed source histories. The observation density is the convolution of independent Gaussian and truncated-Cauchy variables, evaluated by {meta['config']['quadrature_nodes']}-node Gauss-Legendre quadrature with log-sum-exp stabilization. Particle rejuvenation uses tangent-space MALA with a wrapped-Gaussian proposal density; the Metropolis correction always evaluates the exact configured target. A paired 2 × 3 × 3 design crossed analytical versus amortized joint scores, +15/+5/−5 dB, and LOS/minor-multipath/NLOS channels. One hundred trajectory blocks per physical cell yielded 1,800 method runs. Mean frequency MSE was {an.mse_frequency:.2f} Hz² for the analytical score and {su.mse_frequency:.2f} Hz² for the surrogate; the raw paired difference was {overall['mse_frequency'].mean_difference_surrogate_minus_analytical:.2f}, 95% CI [{overall['mse_frequency'].ci95_low:.2f}, {overall['mse_frequency'].ci95_high:.2f}]. SNR, channel, and their interaction were significant after Holm adjustment, whereas architecture was not. The surrogate was slower and had lower MALA acceptance. These findings validate execution and numerical coherence in representative simulation, not operational SIGINT performance.",sty,"body0"),p("<b>Keywords:</b> blind source separation, torus, sequential Monte Carlo, MALA, frequency hopping, multipath, robust likelihood",sty,"body0")],sty,2)
    add_page(story,"Executive Overview",[image("overall.png"),p("Figure 1. Endpoint means expressed relative to the analytical architecture.",sty,"caption"),*bullets([f"Executed scope: {meta['unique_physical_trajectories']} paired physical trajectories and {meta['experimental_rows']} method-level runs.",f"Primary raw-scale contrast: {overall['mse_frequency'].mean_difference_surrogate_minus_analytical:.2f} Hz², with an interval crossing zero.",f"Compute contrast: the surrogate added {overall['latency_ms_per_sample'].mean_difference_surrogate_minus_analytical:.3f} ms per sample.",f"Particle health: mean ESS was {an.particle_ess_mean:.2f} analytical and {su.particle_ess_mean:.2f} surrogate.","Claim boundary: simulation validation is complete; field validation remains unperformed."],sty)],sty,3)
    add_page(story,"Problem and Estimand",[p("Let y<sub>t</sub> be a complex baseband sample formed by two overlapping emitters. At time t, emitter k has latent log amplitude ℓ<sub>k,t</sub>, frequency f<sub>k,t</sub>, channel index z<sub>k,t</sub>, and phase φ<sub>k,t</sub> ∈ T. A tapped complex channel h<sub>k,r,t</sub> combines present and delayed source symbols. The filtering target is p(ℓ<sub>t</sub>, f<sub>t</sub>, z<sub>t</sub>, φ<sub>t</sub>, h<sub>t</sub> | y<sub>1:t</sub>).",sty),p("The primary estimand is the architecture effect on trajectory-averaged two-emitter frequency MSE, paired within physical seed, SNR, and channel. Secondary estimands concern circular phase RMSE, channel NMSE, particle ESS, genealogical diversity, MALA acceptance, resampling count, and synchronized software latency.",sty),p("The comparison is intentionally narrow: both architectures target the same conditional density and use identical particle mechanics. They differ only in the drift supplied to MALA. Consequently, any treatment difference is attributable to the proposal-score operator plus its computational overhead, not to different observation models or priors.",sty),*bullets(["Experimental unit: one simulated physical trajectory under one SNR-by-channel condition.","Repeated block: the same seed indexes every treatment combination.","Treatment levels: analytical joint score and amortized joint surrogate.","Evaluation begins after one hop interval to reduce initialization dominance."],sty)],sty,4)
    add_page(story,"Contributions and Scope",[p("The reconstruction removes the principal contradictions in the earlier reference benchmark. Phase is no longer reconstructed after inference; it is a particle coordinate. Channel gains are no longer supplied from the simulator; they are propagated as latent complex states. Frequency evolution combines a discrete channel switch with continuous local deviation. Finally, the observation density is the convolution law implied by additive Gaussian and truncated-Cauchy components.",sty),p("The MALA kernel is geometrically matched to the state space. Euclidean coordinates use normal forward and reverse densities. Each phase coordinate uses a tangent increment, the flat-torus exponential map, and a lift-summed wrapped normal density. For the flat torus, the metric is constant and the exponential-map Jacobian equals one under Haar volume.",sty),p("The resulting claim is strong but bounded: the broader joint SSM is executed, tested, and benchmarked in operationally representative simulation. The work does not establish performance on recorded emitters, receiver impairments, uncontrolled spectrum occupancy, or deployed hardware.",sty),*bullets(["Supported: numerical normalization, score verification, blind channel isolation, and complete factorial execution.","Unsupported: field detection probability, false-alarm control, hardware throughput, or operational mission utility.","Required next: a preregistered controlled RF campaign with independent truth and blinded analysis."],sty)],sty,5)
    add_page(story,"Joint State-Space Model",[p("Define S<sub>t</sub> = (ℓ<sub>t</sub>, f<sub>t</sub>, z<sub>t</sub>, φ<sub>t</sub>, h<sub>t</sub>, H<sub>t</sub>), where H<sub>t</sub> is the delayed source history. The transition factors as p(z<sub>t</sub>|z<sub>t−1</sub>)p(f<sub>t</sub>|f<sub>t−1</sub>,z<sub>t</sub>,z<sub>t−1</sub>)p(ℓ<sub>t</sub>|ℓ<sub>t−1</sub>)p(φ<sub>t</sub>|φ<sub>t−1</sub>,f<sub>t</sub>)p(h<sub>t</sub>|h<sub>t−1</sub>).",sty),p("The source is s<sub>k,t</sub> = exp(ℓ<sub>k,t</sub> + iφ<sub>k,t</sub>). For tap r with delay d<sub>r</sub>, the clean observation is μ<sub>t</sub> = Σ<sub>k,r</sub> h<sub>k,r,t</sub>s<sub>k,t−d<sub>r</sub></sub>. The complex observation y<sub>t</sub> = μ<sub>t</sub> + ε<sub>t</sub> is evaluated componentwise in the real and imaginary dimensions.",sty),p("A particle approximation {S<sub>t</sub><sup>(j)</sup>, w<sub>t</sub><sup>(j)</sup>} represents the filtering distribution. The true simulator path is absent from the filter API; it is consulted only after filtering to calculate performance responses.",sty),table([["Coordinate","Domain","Executed transition"],["Log amplitude","R²","Mean-reverting Gaussian"],["Frequency","R²","Switch-centered AR Gaussian"],["Hop state","Finite × finite","Markov jump"],["Phase","T²","Wrapped Gaussian"],["Channel","C<sup>2R</sup>","Complex AR Gaussian"]],[1.25*inch,1.15*inch,3.9*inch],sty)],sty,6)
    add_page(story,"Switching Frequency Dynamics",[p("Each emitter occupies one of four nominal channels. The alphabets overlap at 42 and 54 Hz, so instantaneous spectral location alone does not identify emitter labels. At scheduled hop opportunities, z<sub>k,t</sub> changes with probability .34 to a different channel. Between jumps, frequency follows a local autoregression around the current channel center.",sty),p("Let c<sub>k,z</sub> be the center associated with hop state z. If no jump occurs, m<sub>f</sub> = c<sub>k,z</sub> + ρ<sub>f</sub>(f<sub>k,t−1</sub> - c<sub>k,z</sub>). If z changes, m<sub>f</sub> = c<sub>k,z<sub>t</sub></sub>. The executed transition is f<sub>k,t</sub> ∼ N(m<sub>f</sub>, σ<sub>f</sub>²), with ρ<sub>f</sub> = .82 and σ<sub>f</sub> = .42 Hz.",sty),p("This switching construction prevents a continuous diffusion prior from assigning vanishing probability to tactical hops. The hop variable is sampled before continuous frequency, so phase propagation is candidate dependent. The analytical frequency score includes the derivative induced through the phase transition location.",sty),*bullets(["Emitter 1 centers: 18, 30, 42, and 54 Hz.","Emitter 2 centers: 42, 50, 54, and 62 Hz.","All nominal carriers remain below the 64 Hz Nyquist boundary.","Overlap creates genuine co-channel ambiguity at 42 and 54 Hz."],sty)],sty,7)
    add_page(story,"Torus Geometry and Phase Propagation",[p("The phase vector belongs to T² = (R/2πZ)². Given candidate frequency, the transition location is m<sub>φ,t</sub> = φ<sub>t−1</sub> + 2πf<sub>t</sub>Δt. The next phase is the equivalence class of m<sub>φ,t</sub> plus circular Gaussian noise. No discontinuous sawtooth derivative is inserted in the target.",sty),p("For a flat torus, Exp<sub>φ</sub>(v) = (φ + v) mod 2π. The Riemannian metric is the identity, Haar volume is translation invariant, and |det D Exp| = 1. Therefore, no nonconstant metric determinant appears in the proposal ratio. Geometry enters through periodic preimages, not through an invented Jacobian penalty.",sty),p("The wrapped Gaussian density is q<sub>T</sub>(φ*|φ) = Σ<sub>k∈Z²</sub> N(φ* − φ + 2πk; m, Σ). The code evaluates five lifts per phase coordinate (k = −2,…,2). At the configured proposal standard deviation of .04 rad, omitted terms are numerically negligible.",sty),p("Regression tests integrate the wrapped density against [0,2π), compare its score with central finite differences, and verify invariance after adding integer multiples of 2π.",sty)],sty,8)
    add_page(story,"Exact Convolution Noise Law",[p("For one real component, ε = G + C, where G ∼ N(0,σ<sub>G</sub>²) and C is Cauchy(0,γ) truncated to [−A,A]. Hence p<sub>ε</sub>(e) = ∫<sub>−A</sub><sup>A</sup> p<sub>G</sub>(e−τ)p<sub>C</sub>(τ)dτ. This is a convolution-not a Bernoulli mixture-and every generated sample contains both independent components.",sty),p("The implemented evaluator maps 24 Gauss-Legendre nodes to [−A,A]. Node weights, the normalized truncated-Cauchy density, and the Gaussian normalizer are accumulated in log space. logsumexp prevents underflow without changing the probability law through additive floors.",sty),p("The residual score is an expectation under quadrature-normalized node weights: ∂ log p(e)/∂e = Σ<sub>j</sub> ŵ<sub>j</sub>[−(e−τ<sub>j</sub>)/σ<sub>G</sub>²]. This expression is propagated analytically through complex channel coefficients, log amplitude, and phase.",sty),table([["Item","Executed value"],["Cauchy variance fraction","0.10 per real component"],["Truncation","5 standard Cauchy scales"],["Quadrature","24-point Gauss-Legendre"],["Complex likelihood","Independent real and imaginary convolutions"],["Numerical density floor","None"]],[2.2*inch,4.1*inch],sty)],sty,9)
    add_page(story,"Latent Tapped-Delay Channel",[p("The channel state h<sub>k,r,t</sub> is complex. Its transition is h<sub>t</sub> = ρ<sub>h</sub>h<sub>t−1</sub> + (1−ρ<sub>h</sub>)μ<sub>h</sub> + ξ<sub>t</sub>, with ρ<sub>h</sub> = .965 and independent real-imaginary innovation scale .05. Particles therefore preserve uncertainty in gain and phase distortion.",sty),p("LOS has one zero-delay tap. Minor multipath has delays 0 and 2. NLOS uses delays 1 and 4, which removes a direct zero-delay component and forces the filter to use the source history. The particle state includes a lag buffer long enough for the maximum delay.",sty),p("Blindness is enforced structurally: JointParticleFilter.run accepts observation and calibrated noise-law parameters only. It has no argument for true states or realized channels. A regression test inspects this API, and post hoc channel NMSE is computed outside the filter.",sty),table([["Mode","Delays","Interpretation"],["LOS","0","Two latent direct complex coefficients"],["MP","0, 2","Direct plus weaker delayed reflection"],["NLOS","1, 4","Two delayed complex paths; no direct tap"]],[1.1*inch,1.1*inch,4.1*inch],sty)],sty,10)
    add_page(story,"Sequential Particle Filter",[p("At each time step, particles sample the switching, frequency, amplitude, torus phase, channel, and history transitions. The exact convolution likelihood updates log weights. Stable normalization subtracts logsumexp, and particle ESS is 1/Σw<sub>j</sub>².",sty),p("Systematic resampling occurs when ESS falls below .58P or at a forced six-sample move interval. The latter guarantees that both proposal operators are exercised across all conditions. After resampling, one MALA rejuvenation step targets the exact conditional density given the selected ancestor.",sty),p("This is a resample-move particle filter. Particle ESS measures weight concentration; it is not the Markov-chain ESS formula used for long stationary chains. Because the rejuvenation kernel consists of one step per event, rank-normalized R-hat is not meaningful here. We report MALA acceptance and unique ancestors instead.",sty),*bullets(["Particles P = 64.","Samples T = 60.","Resampling threshold = 37.12 effective particles.","Forced move interval = 6 samples.","All posterior summaries are weighted before resampling or equally weighted afterward."],sty)],sty,11)
    add_page(story,"Manifold MALA and Detailed Balance",[p("Let θ contain all Euclidean coordinates and φ the phase pair. The proposal mean is ½ε²s, with s supplied analytically or by the surrogate. Euclidean coordinates follow N(θ + ½ε²s<sub>θ</sub>, ε²I). Phase coordinates follow the wrapped density induced by Exp<sub>φ</sub>.",sty),p("The acceptance probability is α = min{1, exp[log π(x*) − log π(x) + log q(x|x*) − log q(x*|x)]}. Both q terms use the scores evaluated at their respective endpoints. The target π is always the exact configured transition times convolution likelihood, including when the surrogate formed the proposal.",sty),p("For any x and x*, π(x)q(x*|x)α(x,x*) = min{π(x)q(x*|x), π(x*)q(x|x*)}; symmetry establishes detailed balance. Retraction wrapping does not invalidate this equality because q is evaluated as a density with respect to product Lebesgue-Haar volume.",sty),p("Analytical score clipping at ±120 limits extreme drift. Because the actual clipped score is used in both forward and reverse proposal densities, clipping changes proposal efficiency but not the corrected invariant conditional target.",sty)],sty,12)
    add_page(story,"Analytical Joint Score",[p("Transition scores are closed form. The log-amplitude and frequency terms are Gaussian residual scores. The phase score is the lift-weighted derivative of the wrapped transition. The channel score combines its complex AR prior with the exact observation derivative.",sty),p("Candidate frequency affects the target twice: through its switching Gaussian transition and through the phase-transition location φ<sub>t−1</sub> + 2πf<sub>t</sub>Δt. The implemented frequency score includes −2πΔt times the phase residual score. Omitting this term would recreate the state-phase contradiction in the original prototype.",sty),p("For the observation model, differentiation is expressed through real and imaginary directional derivatives. If μ depends on a real coordinate u, then ∂ log p(y−μ)/∂u = −s<sub>R</sub>Re(∂μ/∂u) − s<sub>I</sub>Im(∂μ/∂u), where s is the residual score.",sty),p("A permanent all-coordinate regression test compares the packed analytical score with central finite differences for MP data. In the executed audit, the maximum absolute discrepancy was 7.4 × 10<sup>−9</sup>.",sty)],sty,13)
    add_page(story,"Amortized Joint Surrogate",[p("The alternative proposal uses a SiLU random-feature network. Inputs encode standardized innovations for amplitude, frequency, circular phase, padded complex channel residuals, normalized complex observation residual, candidate state, channel-mode indicators, and noise variance.",sty),p("The hidden map has 72 fixed random SiLU features. Output coefficients are estimated by ridge regression against independently generated exact joint scores. This construction is an amortized differentiable score proxy; it is not treated as a replacement likelihood.",sty),p(f"Training used {meta['surrogate_validation']['training_rows']} rows and validation used {meta['surrogate_validation']['validation_rows']} rows generated independently of the 900 evaluation blocks. Validation score correlation was {meta['surrogate_validation']['validation_score_correlation']:.3f}, with aggregate score RMSE {meta['surrogate_validation']['validation_score_rmse']:.3f}.",sty),p("Metropolis correction protects target invariance from surrogate bias provided the forward and reverse proposal densities use the actual proxy scores. Approximation quality still affects acceptance, mixing, and latency; these are therefore explicit experimental responses.",sty)],sty,14)
    add_page(story,"Physical Simulation Engine",[p("The simulator creates complex I/Q trajectories at 128 Hz. Two emitters have overlapping hop alphabets and stochastic amplitude, frequency, phase, and channel states. The observation channel is LOS, minor multipath, or NLOS tapped delay. The true paths are saved only for evaluation.",sty),p("Noise is calibrated after clean mixing to nominal +15, +5, or −5 dB. Real and imaginary components each receive an independent Gaussian plus truncated-Cauchy sum. Achieved SNR is retained per run because finite samples and heavy tails make nominal and realized power differ.",sty),p("Stable keyed seeds separate physical simulation from inference randomization. For a fixed seed, SNR, and channel, both architectures receive the identical observation trajectory and noise hyperparameters. This pairing eliminates between-trajectory variation from architecture contrasts.",sty),table([["Component","Setting"],["Emitters","2 frequency-hopping complex sources"],["Length","60 complex I/Q samples"],["Hop opportunity","Every 12 samples"],["Particles","64"],["Physical blocks","900"],["Method-level records","1,800"]],[2.1*inch,4.2*inch],sty)],sty,15)
    add_page(story,"Factorial Design",[p("The experiment is a balanced 2 × 3 × 3 full factorial. Factor A is inference architecture. Factor B is nominal SNR (+15, +5, −5 dB). Factor C is channel complexity (LOS, MP, NLOS). Each physical cell contains 100 seed blocks observed under both architectures.",sty),p("All method contrasts are paired by seed, SNR, and channel. The same seed labels also recur across the nine physical conditions, yielding a repeated-measures block over the complete 18-condition profile. Execution order is deterministic, but latency is measured inside each filter and interpreted as implementation-specific software timing.",sty),p("The primary response is MSE<sub>f</sub> = T<sup>−1</sup>Σ<sub>t</sub>||f̂<sub>t</sub>−f<sub>t</sub>||² after the first hop interval. Phase uses circular differences. Channel NMSE divides complex squared error by true channel energy.",sty),table([["Factor","Levels","Role"],["A: score architecture","2","Primary treatment"],["B: SNR","3","Ordered environment"],["C: channel","3","Ordered complexity"],["Seed block","100","Repeated physical randomization"]],[1.5*inch,2.1*inch,2.7*inch],sty)],sty,16)
    add_page(story,"Blocked Contrast Analysis",[p("For inference, each 18-condition seed vector is projected onto a complete orthonormal factorial basis. Architecture uses a normalized two-level contrast. SNR and channel each use normalized linear and quadratic contrasts. Tensor products generate all main effects and interactions.",sty),p("For an effect with q contrast coordinates, the 100 seed-level score vectors are tested against zero using Hotelling’s T² and its exact F transformation: F = (n−q)T²/[q(n−1)], with q and n−q degrees of freedom. This multivariate repeated-measures test avoids a univariate sphericity assumption.",sty),p("Frequency MSE and channel NMSE are log transformed; phase RMSE and particle ESS remain on their natural scales; latency is log transformed. Holm adjustment is applied across the seven omnibus effects within each response. Raw paired mean differences and normal intervals remain descriptive summaries on the original scale.",sty),p("The analysis treats the 100 seed profiles as independent blocks. It does not infer to a population of real receivers or emitters; that external generalization requires a field sampling frame.",sty)],sty,17)
    add_page(story,"Numerical and Structural Verification",[p("Nine automated tests protect the core claims. The convolution density integrates to one, and its score matches central finite differences. The wrapped density integrates to one against torus volume, its score matches finite differences, and phase differences are periodic.",sty),p("The full joint target test perturbs every packed coordinate-log amplitudes, frequencies, phases, real channel taps, and imaginary channel taps-and compares the analytical gradient with the central-difference derivative. The observed maximum absolute difference was 7.4 × 10<sup>-9</sup>.",sty),p("The structural tests enforce Nyquist-valid overlapping channel alphabets and a blind filter API with no truth or true-channel argument. An NLOS end-to-end smoke test verifies finite outputs and constrains phases to [0,2π).",sty),table([["Domain","Tests","Status"],["Convolution law","Normalization; score derivative","Pass"],["Torus geometry","Normalization; derivative; periodicity","Pass"],["Joint target","Nyquist; gradient; API; NLOS smoke","Pass"]],[1.5*inch,3.7*inch,1.0*inch],sty)],sty,18)
    add_page(story,"Primary Frequency-Recovery Results",[image("factorial_mse.png"),p("Figure 2. Mean frequency MSE by SNR, channel, and architecture; bars are 95% normal intervals.",sty,"caption"),p(f"Across all conditions, analytical mean MSE was {an.mse_frequency:.2f} Hz² (SD = {results[results.architecture==ANALYTICAL].mse_frequency.std():.2f}); surrogate mean MSE was {su.mse_frequency:.2f} Hz² (SD = {results[results.architecture==SURROGATE].mse_frequency.std():.2f}). The paired raw difference was {overall['mse_frequency'].mean_difference_surrogate_minus_analytical:.2f}, 95% CI [{overall['mse_frequency'].ci95_low:.2f}, {overall['mse_frequency'].ci95_high:.2f}].",sty),p("Thus, the original-scale paired summary does not establish an overall accuracy difference. Error increases as SNR decreases and as the channel moves from LOS to delayed NLOS. Architecture-specific curves largely overlap relative to these environmental shifts.",sty)],sty,19)
    add_page(story,"Phase and Channel Recovery",[image("phase_channel.png"),p("Figure 3. Circular phase RMSE and complex channel NMSE by SNR and architecture.",sty,"caption"),p(f"Mean phase RMSE was {an.phase_circular_rmse:.3f} rad for the analytical score and {su.phase_circular_rmse:.3f} rad for the surrogate. The paired difference was {overall['phase_circular_rmse'].mean_difference_surrogate_minus_analytical:.3f}, 95% CI [{overall['phase_circular_rmse'].ci95_low:.3f}, {overall['phase_circular_rmse'].ci95_high:.3f}].",sty),p(f"Mean channel NMSE was {an.channel_nmse:.3f} analytical and {su.channel_nmse:.3f} surrogate. The paired difference was {overall['channel_nmse'].mean_difference_surrogate_minus_analytical:.3f}, 95% CI [{overall['channel_nmse'].ci95_low:.3f}, {overall['channel_nmse'].ci95_high:.3f}]. Neither descriptive interval excludes zero." ,sty)],sty,20)
    add_page(story,"Particle Health and Computation",[image("health_compute.png"),p("Figure 4. Mean particle ESS and software latency by SNR and architecture.",sty,"caption"),p(f"Particle ESS averaged {an.particle_ess_mean:.2f} for the analytical method and {su.particle_ess_mean:.2f} for the surrogate. Their paired difference was {overall['particle_ess_mean'].mean_difference_surrogate_minus_analytical:.3f}, 95% CI [{overall['particle_ess_mean'].ci95_low:.3f}, {overall['particle_ess_mean'].ci95_high:.3f}].",sty),p(f"Latency averaged {an.latency_ms_per_sample:.3f} ms/sample analytical and {su.latency_ms_per_sample:.3f} ms/sample surrogate. The paired difference was {overall['latency_ms_per_sample'].mean_difference_surrogate_minus_analytical:.3f}, 95% CI [{overall['latency_ms_per_sample'].ci95_low:.3f}, {overall['latency_ms_per_sample'].ci95_high:.3f}]. Analytical acceptance was {an.mala_acceptance:.3f}; surrogate acceptance was {su.mala_acceptance:.3f}.",sty)],sty,21)
    add_page(story,"Factorial Effects",[image("effects.png",height=2.75*inch),p("Figure 5. Partial eta squared for omnibus effects on log frequency MSE; green effects survive Holm adjustment.",sty,"caption"),table([["Effect","F(df)","Holm p","Partial η²"]]+[[idx,f"{row.F:.2f} ({int(row.df1)}, {int(row.df2)})",("< .001" if row.p_holm_within_response<.001 else f"{row.p_holm_within_response:.3f}"),f"{row.partial_eta_squared:.3f}"] for idx,row in primary.iterrows()],[2.4*inch,1.45*inch,1.1*inch,1.15*inch],sty),p(f"Architecture alone yielded F(1, 99) = {primary.loc['Architecture'].F:.2f}, Holm p = {primary.loc['Architecture'].p_holm_within_response:.3f}. SNR, channel, and SNR × channel survived multiplicity correction. The three-way interaction did not.",sty)],sty,22)
    add_page(story,"Trace-Level Diagnostics and Limitations",[image("trace.png"),p("Figure 6. Predeclared seed-0, +5 dB NLOS frequency trace.",sty,"caption"),image("torus_ess.png",height=2.05*inch),p("Figure 7. Analytical torus phase and particle ESS for the same trace.",sty,"caption"),p("The trace demonstrates execution, not population performance. Posterior means can average competing hop modes and therefore appear between channel centers. Sixty samples and 64 particles are a reproducible benchmark budget, not a sufficiency proof. Label information is partially stabilized by emitter-specific alphabets and dynamics, so unrestricted blind identifiability is not established.",sty)],sty,23)
    add_page(story,"Operational Validation Ladder",[p("Operational validation is an empirical status, not a phrase created by simulator realism. The present study completes numerical verification and representative simulation. It does not include receiver hardware, recorded complex I/Q, lawful controlled emitter schedules, independently maintained truth, or analysts blinded to scenario labels.",sty),table([["Gate","Evidence required","Current status"],["1. Numerical","Normalization, gradients, invariants","Complete"],["2. Simulation","Full factorial with latent channel and heavy tails","Complete"],["3. Hardware-in-loop","Calibrated receiver, clock, quantization, real-time load","Not performed"],["4. Controlled RF","Recorded I/Q and independent emitter/channel truth","Not performed"],["5. External replication","Locked code evaluated by independent team","Not performed"]],[1.35*inch,3.8*inch,1.3*inch],sty),p("A defensible next campaign would preregister scenarios and endpoints, freeze the code and surrogate weights, acquire lawful controlled recordings, separate truth custodians from analysts, measure wall-clock latency on specified hardware, and publish failures as well as successes.",sty),p("Until those gates are complete, all public language should remain: ‘operationally representative simulation validation.’",sty)],sty,24)
    add_page(story,"Reproducibility and Audit Map",[p("The repository separates generator, inference, analysis, site, and report code. Row-level factorial results are immutable CSV artifacts. Metadata records every configured hyperparameter and the independent surrogate validation summary.",sty),table([["Artifact","Purpose"],["src/signals_project/joint_ssm.py","Simulator, exact likelihood, surrogate, torus MALA, joint particle filter"],["tests/test_joint_ssm.py","Eight numerical, geometric, blindness, and smoke tests"],["data/joint_factorial_results.csv","All 1,800 method-level outcomes"],["data/joint_cell_summary.csv","Cell means and standard deviations"],["data/joint_factorial_effects.csv","Blocked multivariate repeated-measures tests"],["data/joint_example_trace.csv","Predeclared interactive trace"],["scripts/build_site.py","Self-contained dashboard builder"],["scripts/build_report.py","This 27-page report builder"]],[2.3*inch,4.2*inch],sty),p("Canonical run: PYTHONPATH=. python -m src.signals_project.joint_ssm --output data --repetitions 100 --particles 64 --samples 60. Then execute scripts/analyze_joint_results.py, scripts/build_site.py, and scripts/build_report.py.",sty,"body0")],sty,25)
    add_page(story,"Conclusions",[p("The reconstruction accomplished the central engineering objective: the broader joint state-space model is no longer merely described. It is executed as a blind resample-move particle filter over switching frequency, torus phase, amplitude, latent complex tapped-delay channels, and source history.",sty),p("The likelihood now matches the additive noise generator through Gaussian-truncated-Cauchy convolution quadrature. The torus proposal uses tangent increments, exponential retraction, and wrapped forward/reverse densities. Both proposal architectures are corrected against the same exact configured target.",sty),p("The factorial evidence attributes most log-frequency error variation to SNR, channel complexity, and their interaction. After Holm adjustment, architecture does not show a primary main effect. The amortized score is slower here and accepts fewer rejuvenation moves, despite high held-out score correlation.",sty),p("These results justify an executed-model and representative-simulation claim. They do not justify operational SIGINT validation. The scientific next step is not stronger wording; it is a preregistered, independently blinded controlled RF campaign on specified hardware.",sty),*bullets(["Use the analytical score as the current reference implementation.","Treat the surrogate as an efficiency research branch, not a validated replacement.","Increase particles and trajectory length in a registered sensitivity study.","Advance validation only when real I/Q and independent truth are available."],sty)],sty,26)
    refs=["Andrieu, C., Doucet, A., & Holenstein, R. (2010). Particle Markov chain Monte Carlo methods. Journal of the Royal Statistical Society: Series B, 72(3), 269-342. https://doi.org/10.1111/j.1467-9868.2009.00736.x","Cranmer, K., Brehmer, J., & Louppe, G. (2020). The frontier of simulation-based inference. Proceedings of the National Academy of Sciences, 117(48), 30055-30062. https://doi.org/10.1073/pnas.1912789117","Doucet, A., de Freitas, N., & Gordon, N. (Eds.). (2001). Sequential Monte Carlo methods in practice. Springer.","Gordon, N. J., Salmond, D. J., & Smith, A. F. M. (1993). Novel approach to nonlinear/non-Gaussian Bayesian state estimation. IEE Proceedings F, 140(2), 107-113.","Roberts, G. O., & Tweedie, R. L. (1996). Exponential convergence of Langevin distributions and their discrete approximations. Bernoulli, 2(4), 341-363.","Särkkä, S. (2013). Bayesian filtering and smoothing. Cambridge University Press.","Vehtari, A., Gelman, A., Simpson, D., Carpenter, B., & Bürkner, P.-C. (2021). Rank-normalization, folding, and localization: An improved R-hat for assessing convergence of MCMC. Bayesian Analysis, 16(2), 667-718. https://doi.org/10.1214/20-BA1221","Wood, S. N. (2010). Statistical inference for noisy nonlinear ecological dynamic systems. Nature, 466, 1102-1104. https://doi.org/10.1038/nature09319"]
    add_page(story,"References",[p(r,sty,"ref") for r in refs]+[Spacer(1,.2*inch),p("Repository-specific note",sty,"h2"),p("All numerical values in this report are computed from the committed joint_factorial_results.csv and associated derived artifacts. References support general methods; none is presented as evidence of operational validation for this implementation.",sty,"body0")],sty,27)
    doc=SimpleDocTemplate(str(PDF),pagesize=LETTER,rightMargin=.72*inch,leftMargin=.78*inch,topMargin=.68*inch,bottomMargin=.68*inch,title="Signals Project: Executed Blind De-Mixing With a Joint Torus-Valued State-Space Model",author="Signals Project Research Group",subject="Computational statistics simulation validation")
    doc.build(story,onFirstPage=page_number,onLaterPages=page_number)


if __name__ == "__main__":
    main()
